# Cli tools
brew "bat"              # less
brew "btop"             # top
brew "eza"              # ls
brew "fd"               # find
brew "fzf"              # fuzzy finder
brew "glow"             # pretty markdown
brew "just"             # make
brew "jq"               # json manipulation
brew "ripgrep"          # silver surfer
brew "rnr"              # renamer
brew "tealdeer"         # tldr
brew "uutils-coreutils" # coreutils
brew "wget"
brew "yq"               # yaml manipulation

brew "chezmoi" # config sync

# editors
brew "neovim"
cask "vscodium"

# dev tooling
cargo "difftastic"
cargo "tilt"

# rust tooling
cargo "bacon"           # watcher
cargo "cargo-nextest"   # better test runner
cargo "samply"          # rust profiling
cargo "wasm-pack"

# code
brew "fnm" # node manager
brew "uv"

# terminal
cask "iterm2"
cask "wezterm@nightly"
brew "zellij"

# shells
brew "bash"
brew "fish"

# vcs
brew "git"
brew "gh"
brew "jujutsu"

# cloud
brew "awscli"
cask "gcloud-cli"
brew "kubernetes-cli"
brew "k9s"
brew "kubectx"
brew "pulumi"
